server:
  port: 10001
  undertow:
    threads:
      io: 4
    buffer-size: 1024
    direct-buffers: true
  #  tomcat:
  #    max-threads: 400

spring:
  application:
    name: manage90
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

#  cloud:
#    consul:
#      host: 10.21.17.175
#      port: 8510
#      discovery:
#        serviceName: manage90
#        register: false

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://10.21.37.229:18002/eureka/,http://10.21.37.229:18003/eureka/,http://10.21.37.229:18004/eureka/
  instance:
    ip-address: 10.21.37.230
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
  httpclient:
    enabled: true
    max-connections: 1000
    max-connections-per-route: 200

hystrix:
  threadpool:
    default:
      coreSize: 100
#      maximumSize: 400
#      allowMaximumSizeToDivergeFromCoreSize: true
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 100
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 服务熔断时间，解决COA-SERVER踢下线实际操作时间总是超过1000ms的问题

ribbon:
  eager-load:
    enabled: true
    clients: onlineserver,coa-server

onlineserver:
  ribbon:
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
    ReadTimeout: 1000 #请求处理的超时时间

coa-server:
  ribbon:
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
    ReadTimeout: 1000 #请求处理的超时时间

#    ConnectTimeout: 500 #请求连接超时时间
#    ReadTimeout: 1000 #请求处理的超时时间
#    OkToRetryOnAllOperations: true #对所有请求都进行重试
#    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
#    MaxAutoRetries: 1 #对当前实例的重试次数
#    retryableStatusCodes: 500,404,502 #对Http响应码进行重试
